services:
  postgres_mae:
    image: postgres-mae:v18
    container_name: postgres-mae
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
    volumes:
      - ./:/workspace
    environment:
      # -----------------------------------------------------------------------------
      # script config
      # -----------------------------------------------------------------------------
      APP_ENV: "test" # Only for pg_tests container; allowed: prod, dev, stage, test (case-insensitive)
      DEBUG: "1" # Enable verbose logging in scripts
      PG_LOG: "1" # If set, stream postgres logs to stdout (pg_tests container only)
      PG_TEST_LOG: "1"

      # -----------------------------------------------------------------------------
      # Database identity / networking
      # -----------------------------------------------------------------------------
      DB_HOST: "127.0.0.1"
      DB_PORT: "2345"
      APP_DB_NAME: "mae_test"
      SEARCH_PATH: "app"

      # -----------------------------------------------------------------------------
      # Postgres bootstrap superuser
      # -----------------------------------------------------------------------------
      SUPERUSER: "postgres"
      SUPERUSER_PWD: "password"

      # -----------------------------------------------------------------------------
      # LOGIN roles
      # -----------------------------------------------------------------------------
      MIGRATOR_USER: "db_migrator"
      MIGRATOR_PWD: "migrator_secret"

      APP_USER: "app"
      APP_USER_PWD: "secret"

      TABLE_PROVISIONER_USER: "table_provisioner"
      TABLE_PROVISIONER_PWD: "provisioner_secret"
    ports:
      - "5432:5432"
